#!/bin/bash

# Desenvolvido por: Bee Solutions
# Autor: Fernando Almondes
# Data: 15/08/2023

ip=$1
usuario=$2
senha=$3
porta=$4
servico=$5

sshpass -p$senha ssh -o "StrictHostKeyChecking=no" -p$porta $usuario@$ip "interface pppoe-server print terse" | sed -r '/^\s*$/d' | awk '{print $5}' | sed 's/service=//g' | grep -w -c $servico