#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Uso: $0 <comunidade> <ip> <porta>"
    echo "Exemplo: $0 public@dude 10.0.102.3 161"
    exit 1
fi

comunidade=$1
ip=$2
porta=$3

# Define o diretório de trabalho para onde está o executável e o arquivo de descrições
cd /usr/lib/zabbix/externalscripts/vlans_huawei

# Executa o programa Go com um tempo limite de 60 segundos
timeout 30 ./vlans_decobertas "$comunidade" "$ip" "$porta"

# Verifica o status de saída do timeout para detectar se houve um timeout
if [ $? -eq 124 ]; then
    echo "Erro: Tempo limite excedido ao executar o script Go"
    exit 1
fi
