#!/bin/bash

# Verifica se o número correto de argumentos foi fornecido
if [ "$#" -ne 4 ]; then
    echo "Uso: $0 <comunidade> <ip> <porta> <index>"
    echo "Exemplo: $0 public@dude 10.0.102.3 161 115.0.1000"
    exit 1
fi

# Atribui os argumentos a variáveis
comunidade=$1
ip=$2
porta=$3
index=$4

# Define o diretório de trabalho para onde está o executável
cd /usr/lib/zabbix/externalscripts/vlans_huawei

# Executa o programa Go com os parâmetros
./vlans_decobertas "$comunidade" "$index" "$porta"
