#!/bin/bash

# Desenvolvido por: Bee Solutions
# Autor: Fernando Almondes
# Data: 15/08/2023

# Comando de verificação das informações sobre o PPPoE Server (Nome e Interface vinculada)
# interface pppoe-server server print

# Comando para contagem por nome do PPPoE Server
# interface pppoe-server print terse

# Variaveis que vou cadastrar no Zabbix como Macros
ip=$1
usuario=$2
senha=$3
porta=$4
cmd="interface pppoe-server server print"

#awk -F'=' '{print $2,$3}' = Service Name, Nome Interface
#awk -F'=' '{print $3}' = Interface

# Ex: lista_geral=ONU_Digistar;vlan1500-Digistar | interface=vlan1500-Digistar
lista_geral=$(sshpass -p"$senha" ssh -o "StrictHostKeyChecking=no" -p$porta "$usuario"@"$ip" "$cmd"| grep service-name | grep -v -w '[X|I]' | awk -F'=' '{print $2,$3}' | sed 's/ interface /;/g' | sed -E 's/[^[:print:]]//g' | sed 's/ max.*//g' | sed 's/ //g' | sed 's/"//g')
interface=$(sshpass -p"$senha" ssh -o "StrictHostKeyChecking=no" -p$porta "$usuario"@"$ip" "$cmd"| grep service-name | grep -v -w '[X|I]' | awk -F'=' '{print $3}' | sed 's/ interface /;/g' | sed -E 's/[^[:print:]]//g' | sed 's/ max.*//g' | sed 's/ //g' | sed 's/"//g')

# Iniciando o Json
echo [

# Fazendo a contagem de linhas
last_line=$(echo "$lista_geral" | wc -w)

# Analisando a lista geral
for i in $lista_geral
do

# Crio a variavel current_lines e a incremento a cada rodada
current_lines=$(($current_lines + 1))

# Analisando a lista interface
for j in $interface
do

# Verificando se é a última linha
if [[ $current_lines -ne $last_line ]]; then

#Ex: $i=ONU_Digistar;vlan1500-Digistar | $current_lines=1 | $j=vlan1500-Digistar
echo $i | awk -v awkvar=$j -v awkvar2=$current_lines -F ";" '{ if($2==awkvar) print "{\"{#BEEID}\":\""awkvar2"\",\"{#SERVICENAME}\":\""$1"\",\"{#SERVICEINTERFACE}\":\""$2"\"}," }'

else

echo $i | awk -v awkvar=$j -v awkvar2=$current_lines -F ";" '{ if($2==awkvar) print "{\"{#BEEID}\":\""awkvar2"\",\"{#SERVICENAME}\":\""$1"\",\"{#SERVICEINTERFACE}\":\""$2"\"}" }'

fi

done

done

echo ]