#!/bin/bash

if [ "$#" -ne 4 ]; then
    echo "Uso: $0 <comunidade> <ip_host> <porta> <ip_especifico>"
    exit 1
fi

comunidade=$1
ip_host=$2
porta=$3
ip_especifico=$4

/opt/asnname/venv/bin/python3 /opt/asnname/status_as.py "$comunidade" "$ip_host" "$porta" "$ip_especifico"
